ASSIGMENT NUMPY 

question 1
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [15]:
import numpy as np

list_:
The list_ variable is a Python built-in data structure.
It can hold elements of different data types (e.g., integers, strings, floats) within the same list.
Lists are dynamic and allow appending elements, changing their size, and accommodating various data types.
array_list:
The array_list variable is a NumPy array (specifically, a numpy.ndarray).
NumPy arrays are homogeneous, meaning all elements must have the same data type (e.g., all integers, all floats).
NumPy arrays are more memory-efficient and optimized for numerical operations (e.g., vectorized computations)

In [16]:
import numpy as np

# Example lists
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types
print(f"Data type of 'list_': {type(list_)}")
print(f"Data type of 'array_list': {type(array_list)}")


Data type of 'list_': <class 'list'>
Data type of 'array_list': <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [17]:
import numpy as np

# Example lists
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of each element
for element in list_:
    print(f"Data type of '{element}': {type(element)}")

for element in array_list:
    print(f"Data type of '{element}': {type(element)}")


Data type of '1': <class 'str'>
Data type of '2': <class 'str'>
Data type of '3': <class 'str'>
Data type of '4': <class 'str'>
Data type of '5': <class 'str'>
Data type of '1': <class 'numpy.str_'>
Data type of '2': <class 'numpy.str_'>
Data type of '3': <class 'numpy.str_'>
Data type of '4': <class 'numpy.str_'>
Data type of '5': <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [19]:


# Example lists
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of each element in 'list_'
for element in list_:
    print(f"Data type of '{element}': {type(element)}")

# Print data types of each element in 'array_list'
for element in array_list:
    print(f"Data type of '{element}': {type(element)}")


Data type of '1': <class 'str'>
Data type of '2': <class 'str'>
Data type of '3': <class 'str'>
Data type of '4': <class 'str'>
Data type of '5': <class 'str'>
Data type of '1': <class 'numpy.int64'>
Data type of '2': <class 'numpy.int64'>
Data type of '3': <class 'numpy.int64'>
Data type of '4': <class 'numpy.int64'>
Data type of '5': <class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [20]:


# Create your num_array (replace this with your actual data)
num_array = np.array([[1, 2, 3], [4, 5, 6]])

# (i) Shape of num_array
shape = num_array.shape
print(f"Shape of num_array: {shape}")

# (ii) Size of num_array
size = num_array.size
print(f"Size of num_array: {size}")


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [31]:
s = 3,3
array = np.zeros(s)
array


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [32]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

print("Identity Matrix (5x5):")
print(identity_matrix)


Identity Matrix (5x5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
